---
- hosts: webservers
  gather_facts: true
  become: true
  vars_files:
    - vars/vars.yml
  roles:
    - apache
    - php

- hosts: dbservers
  gather_facts: true
  become: true
  roles:
    - mysql


